import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import routes from './src/data/routes.json';

// Replaces a marker comment in each page with a partial from
// src/partials/. Runs 'pre' so Vite's own %VITE_*% env replacement still
// applies to the injected analytics snippets.
function partial(marker: string, file: string): Plugin {
  const partialPath = resolve(__dirname, 'src/partials', file);
  return {
    name: `apn-partial-${file}`,
    transformIndexHtml: {
      order: 'pre',
      handler: (html) => html.replace(`<!-- ${marker} -->`, readFileSync(partialPath, 'utf8')),
    },
  };
}

export default defineConfig({
  plugins: [
    react(),
    // Favicons, fonts, GTM and the Meta Pixel.
    partial('shared-head', 'head-shared.html'),
    // GTM / Meta Pixel <noscript> fallbacks.
    partial('shared-body', 'body-shared.html'),
  ],
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    rollupOptions: {
      // One HTML file per route, generated by scripts/build-pages.mjs.
      input: Object.fromEntries(
        routes.map((r) => [r.page, resolve(__dirname, `.${r.path}index.html`)]),
      ),
    },
  },
});
