import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { imagetools } from 'vite-imagetools';
import routes from './src/data/routes.json';
import { loadPosts } from './src/blog/load-posts';

// Serves the /blog/ pages on the dev server, rendered the same way the
// build does (src/blog-server.tsx) but including drafts, so a post can be
// previewed before it's published. Posts are re-read on every request:
// edit the Markdown and refresh. (From the landing page repo.)
function blogDevServer(): Plugin {
  return {
    name: 'apn-blog-dev',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        const url = (req.url ?? '').split('?')[0];
        if (!/^\/blog(\/[a-z0-9-]+)?\/?$/.test(url)) return next();
        if (!url.endsWith('/')) {
          res.statusCode = 301;
          res.setHeader('Location', `${url}/`);
          return res.end();
        }
        try {
          const raw = readFileSync(resolve(__dirname, 'blog/index.html'), 'utf8');
          const template = await server.transformIndexHtml(url, raw);
          const { renderBlogPages } = (await server.ssrLoadModule(
            '/src/blog-server.tsx',
          )) as typeof import('./src/blog-server');
          const page = renderBlogPages(template, { includeDrafts: true }).find((p) => p.path === url);
          if (!page) return next();
          res.setHeader('Content-Type', 'text/html; charset=utf-8');
          res.end(page.html);
        } catch (err) {
          server.ssrFixStacktrace(err as Error);
          next(err);
        }
      });
    },
  };
}

// Replaces a marker comment in each page with a partial from
// src/partials/. Runs 'pre' so Vite's own %VITE_*% env replacement still
// applies to the injected analytics snippets.
function partial(marker: string, file: string): Plugin {
  const partialPath = resolve(__dirname, 'src/partials', file);
  return {
    name: `apn-partial-${file}`,
    transformIndexHtml: {
      order: 'pre',
      handler: (html) => html.replace(`<!-- ${marker} -->`, readFileSync(partialPath, 'utf8')),
    },
  };
}

// Same photo pipeline as the landing page repo (APNRE-Website), so the
// two sites treat photos the same way. A `?photo` import (see
// src/lib/photo.ts) becomes WebP plus a JPEG fallback at quality 80, at
// the original size plus an 800px-wide copy for photos over 1000px,
// which is what phones load (src/components/Picture.tsx). Other image
// imports are left alone.
//
// The format must be spelled "jpeg", not "jpg": imagetools names a
// freshly made file after the directive but a cached one after what
// sharp reads back ("jpeg"), so with "jpg" a cold-cache client build and
// a warm-cache SSR build disagree on the file names.
const PHONE_PHOTO_WIDTH = 800;
const RESIZE_ABOVE_WIDTH = 1000;

function photoDefaults() {
  return imagetools({
    defaultDirectives: async (url, metadata) => {
      if (!url.searchParams.has('photo')) return new URLSearchParams();
      const { width = 0 } = await metadata();
      const widths = width > RESIZE_ABOVE_WIDTH ? [PHONE_PHOTO_WIDTH, width] : [width];
      return new URLSearchParams({ format: 'webp;jpeg', quality: '80', w: widths.join(';'), as: 'picture' });
    },
  });
}

export default defineConfig({
  plugins: [
    react(),
    photoDefaults(),
    // Favicons, GTM and the Meta Pixel.
    partial('shared-head', 'head-shared.html'),
    // Each page has one of these two markers (scripts/build-pages.mjs):
    // Google Fonts for the main site, self-hosted fonts for /landlords/.
    partial('fonts-agency', 'fonts-agency.html'),
    partial('fonts-landlords', 'fonts-landlords.html'),
    // GTM / Meta Pixel <noscript> fallbacks.
    partial('shared-body', 'body-shared.html'),
    blogDevServer(),
  ],
  define: {
    // Whether any post is published, so the landlord page's footer only
    // links to the blog once there's something to read. Worked out when
    // the build (or dev server) starts.
    __BLOG_HAS_POSTS__: JSON.stringify(loadPosts().length > 0),
  },
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    rollupOptions: {
      // One HTML file per route, generated by scripts/build-pages.mjs and
      // filled in with each page's markup by scripts/prerender.mjs, plus
      // the template every blog page is made from.
      input: {
        ...Object.fromEntries(routes.map((r) => [r.page, resolve(__dirname, `.${r.path}index.html`)])),
        blog: resolve(__dirname, 'blog/index.html'),
      },
    },
  },
});
